security:
  oauth2:
    authorization-server-url: ${env.security.oauth2.authorization-server-url}
    enabled: ${env.security.oauth2.enabled}
    credentials:
      clientId: ${env.security.oauth2.credentials.clientId}
      secret: ${env.security.oauth2.credentials.secret}
    paths:
      code: ${env.security.oauth2.paths.code}
      authorize: ${env.security.oauth2.paths.authorize}
      home: ${env.security.oauth2.paths.home}
    scopes:
      read: ${env.security.oauth2.scopes.read}
      write: ${env.security.oauth2.scopes.write}
    cors:
      origins: ${env.security.oauth2.cors.origins}
      methods: ${env.security.oauth2.cors.methods}
  paths:
    exclude: ${env.security.paths.exclude}
    include: ${env.security.paths.include}
---
spring:
  security:
    user:
      name: ${env.spring.security.user.name}
      password: ${env.spring.security.user.password}
