server:
  servlet:
    context-path: /albaran-digital
spring:
  main:
    allow-bean-definition-overriding: true
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  profiles:
    group:
      pro-csrf: pro, csrf
      dev-csrf: dev, csrf
      dev-insecure: dev, insecure
