env:
  security:
    csrf:
      enabled: true
      cookie:
        domain: localhost
        name: 'CSRF-TOKEN'
        httOnly: false
        secure: false
    oauth2:
      authorization-server-url: http://127.0.0.1:8080
      enabled: true
      credentials:
        clientId: albaran-client
        secret: secret
      paths:
        code: /login/oauth2/code/albaran-client-oidc
        authorize: /login/authorized
        home: /welcome
      scopes:
        read: albaran.read
        write: albaran.write
      cors:
        origins: http://localhost:4200
        methods: GET,POST,PUT,DELETE,OPTIONS
    paths:
      exclude: "/static/**,/signup,/login,/,/favicon.ico,/**.css,/**.scss,/**.html,/**.js"
      include: "/api/**"
  spring:
    security:
      user:
        name: hugo
        password: oguh
---
logging:
  level:
    com.proin.albaran: INFO
    com.proin.albaran.service.log: TRACE #log frontend
    com.proin.albaran.configuration.security: DEBUG
    org.springframework.security: INFO
    org.springframework.security.web: DEBUG
    org.springframework.security.config: DEBUG
    org.springframework.security.oauth2: DEBUG
    com.proin.albaran.configuration.frontend: DEBUG