server:
  servlet:
    context-path: /albaran-digital
spring:
  main:
    allow-bean-definition-overriding: true       
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: none
    generate-ddl: false
    
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver

  profiles:
    group:
      pro-csrf: pro, csrf
      dev-csrf: dev, csrf
      dev-insecure: dev, insecure