spring:
  datasource:
    url: jdbc:sqlserver://85.215.195.246:1433;databaseName=conex.modelos.transporte;encrypt=false;trustServerCertificate=false
    username: albarandigital
    password: albarandigital
logging:
  level:
    org.springframework.security: DEBUG    